### ISSUE TITLE
Integrate simulated time into drools rules 

### ISSUE THREAD

**Issue by dandrid** [IncQueryLabs/smarthome-cep-demonstrator#10]
* [x] Use HomeIO SDK Date time to assign new time stamps
* [x] Automatic lights switch off ( large time window )
* [x] Use an external service for sunrise calculation trough ESH binding

**Comment by rafluq** [comment]
Hi, my name is Rafael and I'm doing a project for university about home i/o and openhab. I'm looking for information and help about this project to write the code, could you help me? Thank you very much

**Comment by dandrid** [comment]
Hi @rafluqber95!
If you just want to use HomeIO in ObenHAB, you need [the OpenHAB HomeIO MQTT bridge](https://github.com/IncQueryLabs/openhab-homeio-mqtt-bridge) project. To sum up, that project connects to HomeIO through the HomeIO SDK, registers for HomeIO events (e.g. devices changes), converts the events into an OpenHAB acceptable format, and sends through MQTT topics. It also listens to events coming from OpenHAB through MQTT and converts them into a HomeIO acceptable format, and executes the changes. 

However, OpenHAB needs to be configured in order to use MQTT and the items representing the HomeIO devices also needs to be in the configuration. This project (Smarthome Cep Demonstrator), adds a new rule engine to OpenHAB called [Drools](https://www.drools.org/), and there are also automation rules created for HomeIO in this Drools rule engine. I don't think you will need this part, but this project also contains OpenHAB configuration files, which can be good for you [here](https://github.com/IncQueryLabs/smarthome-cep-demonstrator/tree/master/smarthome-simulator/HomeIO/homeio-resources/distro-resources/src/main/resources). From here, the HomeIO related config files (**.items**), and the MQTT service configuration files (**.cfg**), can be used for you. You have to put them into your OpenHAB config folder.

If you need help in something else. I will try to help.

**Comment by rafluq** [comment]
Hi András,

Thank you very much for your response. I have configured Mosquitto on OpenHAB, and I’m trying to use “openhab-homeio-mqtt-bridge-master” on VisualStudio but I have a problem:

[cid:image002.png@01D4A3B5.E11BF1A0]

I can’t find M2Mqtt.net library to run the Project. How could I solve it?

Thank you very much for your help again. Happy new year.

Best regards,

Rafael

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: András Jankó <notifications@github.com>
Enviado: Thursday, January 3, 2019 2:07:14 AM
Para: IncQueryLabs/smarthome-cep-demonstrator
Cc: rafluqber95; Mention
Asunto: Re: [IncQueryLabs/smarthome-cep-demonstrator] Integrate simulated time into drools rules (#10)


Hi @rafluqber95<https://github.com/rafluqber95>!
If you just want to use HomeIO in ObenHAB, you need the OpenHAB HomeIO MQTT bridge<https://github.com/IncQueryLabs/openhab-homeio-mqtt-bridge> project. To sum up, that project connects to HomeIO through the HomeIO SDK, registers for HomeIO events (e.g. devices changes), converts the events into an OpenHAB acceptable format, and sends through MQTT topics. It also listens to events coming from OpenHAB through MQTT and converts them into a HomeIO acceptable format, and executes the changes.

However, OpenHAB needs to be configured in order to use MQTT and the items representing the HomeIO devices also needs to be in the configuration. This project (Smarthome Cep Demonstrator), adds a new rule engine to OpenHAB called Drools<https://www.drools.org/>, and there are also automation rules created for HomeIO in this Drools rule engine. I don't think you will need this part, but this project also contains OpenHAB configuration files, which can be good for you here<https://github.com/IncQueryLabs/smarthome-cep-demonstrator/tree/master/smarthome-simulator/HomeIO/homeio-resources/distro-resources/src/main/resources>. From here, the HomeIO related config files (.items), and the MQTT service configuration files (.cfg), can be used for you. You have to put them into your OpenHAB config folder.

If you need help in something else. I will try to help.

**Comment by dandrid** [comment]
Hi @rafluqber95!

M2Mqtt.net library is acquired through Visual Studio NuGet packages. This means, it should be downloaded by VS. If it wasn't, maybe [this thread will help](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore-troubleshooting#quick-solution-for-visual-studio-users), to download it automatically. I think you can also download this package manually, by right clicking on the solution, and **Restore NuGet packages**.

I temporary set my email to public on [my GitHub profile](https://github.com/dandrid). Please contact me there, if you need help in anything else.
